 # pull official base image
FROM python:3.6-alpine

# set work directory
WORKDIR /User

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /User/requirements.txt
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.sh /User/entrypoint.sh


# copy project
COPY . /User
COPY /.env /.env

# run entrypoint.sh
ENTRYPOINT ["/User/entrypoint.sh"]

